services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  nats:
    image: nats:2
    container_name: nats
    ports:
      - "4222:4222"
    restart: unless-stopped
  app:
    build:
      context: .
      args:
        - DB_NAME=${DB_NAME}
        - URI=${URI}
        - GRPC_PORT=${GRPC_PORT}
        - NATS_URL=${NATS_URL}
        - ENDPOINT=${ENDPOINT}
        - REGION=${REGION}
        - ACCESSKEY=${ACCESSKEY}
        - SECRETEKEY=${SECRETEKEY}
        - BUCKET=${BUCKET}
    container_name: article-tags
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      - URI=${URI}
      - DB_NAME=${DB_NAME}
      - GRPC_PORT=${GRPC_PORT}
      - STOPWORDS_PATH=/app/internal/pkg/stopwords.txt
      - NATS_URL=${NATS_URL}
      - ENDPOINT=${ENDPOINT}
      - REGION=${REGION}
      - ACCESSKEY=${ACCESSKEY}
      - SECRETEKEY=${SECRETEKEY}
      - BUCKET=${BUCKET}
    restart: unless-stopped
    depends_on:
      - mongo
      - nats

volumes:
  mongo_data: