// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/article.proto

package article

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleService_ProcessArticles_FullMethodName = "/article.ArticleService/ProcessArticles"
	ArticleService_TopTags_FullMethodName         = "/article.ArticleService/TopTags"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	ProcessArticles(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArticleRequest, ArticleResponse], error)
	TopTags(ctx context.Context, in *TopTagsRequst, opts ...grpc.CallOption) (*TopTagResponse, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) ProcessArticles(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArticleRequest, ArticleResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArticleService_ServiceDesc.Streams[0], ArticleService_ProcessArticles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArticleRequest, ArticleResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArticleService_ProcessArticlesClient = grpc.ClientStreamingClient[ArticleRequest, ArticleResponse]

func (c *articleServiceClient) TopTags(ctx context.Context, in *TopTagsRequst, opts ...grpc.CallOption) (*TopTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopTagResponse)
	err := c.cc.Invoke(ctx, ArticleService_TopTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility.
type ArticleServiceServer interface {
	ProcessArticles(grpc.ClientStreamingServer[ArticleRequest, ArticleResponse]) error
	TopTags(context.Context, *TopTagsRequst) (*TopTagResponse, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServiceServer struct{}

func (UnimplementedArticleServiceServer) ProcessArticles(grpc.ClientStreamingServer[ArticleRequest, ArticleResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessArticles not implemented")
}
func (UnimplementedArticleServiceServer) TopTags(context.Context, *TopTagsRequst) (*TopTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopTags not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}
func (UnimplementedArticleServiceServer) testEmbeddedByValue()                        {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	// If the following call panics, it indicates UnimplementedArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_ProcessArticles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArticleServiceServer).ProcessArticles(&grpc.GenericServerStream[ArticleRequest, ArticleResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArticleService_ProcessArticlesServer = grpc.ClientStreamingServer[ArticleRequest, ArticleResponse]

func _ArticleService_TopTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopTagsRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).TopTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_TopTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).TopTags(ctx, req.(*TopTagsRequst))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "article.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopTags",
			Handler:    _ArticleService_TopTags_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessArticles",
			Handler:       _ArticleService_ProcessArticles_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/article.proto",
}
